import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Nav} from "@/components/nav";
import Providers from "@/components/Providers";
import React from "react";
const inter = Inter({ subsets: ['latin'] })
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + "text-slate-900 dark:bg-slate-900"}>
              <ThemeProvider attribute="class" defaultTheme="light">
                  <Providers>
                      <Nav />
                      {children}
                  </Providers>
              </ThemeProvider>
      </body>
    </html>
  )
}