/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TDtNK34DAv1
 */
"use client"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import AnimalCard from "@/components/animal/AnimalCard";
import {useQuery} from "@apollo/client";
import Image from "next/image";
import { GET_ANIMALS_BY_NAME } from "@/graphql/queries";
import SearchInput from "@/components/SearchInput";

export function Landing() {

  const names = ["dog", "eagle", "gorilla", "cat"];

  const { data, loading, error } = useQuery(GET_ANIMALS_BY_NAME, {
    variables: { names }
  });

  const animals : any = data?.animalsByNames;

  if(loading) return <p>Loading...</p>

  if(error) return <p>{error.message}</p>

  return (
    <>
      <section
        className="w-full h-screen flex flex-col justify-evenly"
      >
        <div className="flex flex-col justify-center items-center h-full">
          <h1 className="text-5xl font-bold">Welcome to Animal Kingdom Database</h1>
          <p className="text-xl">Discover more about your favorite animals</p>
          <div className="mt-8 flex">
            <SearchInput />
          </div>
        </div>
        <div className="p-8 w-4/5 mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 mt-6 relative">
          {animals && animals.map((animal : any) => (
              <Link className="relative" key={animal.id} href={`/animal/${animal.name}`}>
                <AnimalCard key={animal.id} animal={animal} />
              </Link>
          ))}
        </div>
      </section>
      <footer className="w-full bg-slate-800 dark:bg-slate-950 text-white py-8">
        <div className="container mx-auto px-4">
          <div className="flex justify-between items-center">
            <p className="text-sm">© 2023 Animal Database. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </>
  )
}