/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TDtNK34DAv1
 */
"use client"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import AnimalCard from "@/components/animal/AnimalCard";
import {useQuery} from "@apollo/client";
import Image from "next/image";
import { GET_ANIMALS_BY_NAME } from "@/graphql/queries";
import SearchInput from "@/components/SearchInput";

export function Landing() {

  const names = ["dog", "eagle", "gorilla", "cat"];

  const { data, loading, error } = useQuery(GET_ANIMALS_BY_NAME, {
    variables: { names }
  });

  const animals : any = data?.animalsByNames;

  if(loading) return <p>Loading...</p>

  if(error) return <p>{error.message}</p>

  return (
    <>
      <section
        className="w-full min-h-screen flex flex-col justify-evenly"
      >
        <div className="px-8 flex flex-col justify-center items-center">
          <h1 className="text-4xl md:text-5xl font-bold">Discover more about your favorite animals</h1>
          <div className="flex mt-12 w-1/2 mx-auto">
            <SearchInput />
          </div>
        </div>
        <div className="px-8 w-full md:w-4/5 mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 relative">
          {animals && animals.map((animal : any) => (
              <Link className="relative" key={animal.id} href={`/animal/${animal.name}`}>
                <AnimalCard key={animal.id} animal={animal} />
              </Link>
          ))}
        </div>
      </section>
    </>
  )
}